image: jangrewe/gitlab-ci-android:31

# Для перевода ключа подписи в строку (сразу копируется в буфер)
# base64 release.jks | pbcopy


# Количество последних коммитов при клонировании репозитория
# Ускоряет время выполнения пайплайна
variables:
  GIT_DEPTH: 1

stages:
   - buildMR
  #- printCertificates
  #- buildAndTest
  #- testCoverage
  #- incrementVersionCode
  #- deploy

build develop when merge_requests:
  stage: buildMR
  script:
    - ./gradlew app:assembleDebug
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
