image: jangrewe/gitlab-ci-android:33

# Для перевода ключа подписи в строку (сразу копируется в буфер)
# base64 release.jks | pbcopy


# Количество последних коммитов при клонировании репозитория
# Ускоряет время выполнения пайплайна
variables:
  GIT_DEPTH: 1

stages:
   - buildMR
   - buildRelease
  #- printCertificates
  #- buildAndTest
  #- testCoverage
  #- incrementVersionCode
  #- deploy

build develop when merge_requests:
  stage: buildMR
  script:
    - ./gradlew app:assembleDebug
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

# Тригериться только на ручной запуск
build release apk:
  stage: buildRelease
  script:
    #- ./gradlew app:assembleDebug
    - touch union_version_3.0.apk
    - ls
    #- cd app/build/outputs/apk/debug
    - curl -v --location --request POST 'https://api.telegram.org/bot$BOT_KEY/sendDocument?chat_id=$CHAT_ID' --form document=@union_version_3.0.apk
  when: manual

