image: jangrewe/gitlab-ci-android:33

# Для перевода ключа подписи в строку (сразу копируется в буфер)
# base64 release.jks | pbcopy


# Количество последних коммитов при клонировании репозитория
# Ускоряет время выполнения пайплайна
variables:
  GIT_DEPTH: 1

stages:
   - buildMR
   - buildRelease
   - addCommentTrelloCards
  #- printCertificates
  #- buildAndTest
  #- testCoverage
  #- incrementVersionCode
  #- deploy

testTrelloIntegration: 
  stage: addCommentTrelloCards
  tags:
    - android
  script:
    - files=( Rocket_Bot/releaseJar/*.jar )
    - java -jar Rocket_Bot/releaseJar/UnionTrelloIntegrate-1.0-SNAPSHOT.jar "$TRELLO_TOKEN" "$TRELLO_API_KEY" "${files[0]}" "$TRELLO_LIST_ID"
  when: manual

build develop when merge_requests:
  stage: buildMR
  tags:
    - android
  script:
    - ./gradlew app:assembleDebug
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"

# Тригериться только на ручной запуск
build release apk:
  tags:
    - android
  stage: buildRelease
  script:
    - git config --global user.email "gitlab@itrokcet.com"
    - git config --global user.name "Gitlab CI"
    
    # Установка ssh агента если он еще не установлен
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    # Запуск  shh агента
    - eval $(ssh-agent -s)

    # Копируем приватный ключ из переменной CI в id_rsa
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa

    # Записываем в ssh конфиг инфу о том чтобы он не проверял host, по другому на CI работать не будет
    - echo -e "Host *\nStrictHostKeyChecking no" > ~/.ssh/config

    # Удаляем текущие файлы
    - cd ..
    - rm -rf unionandroid

    - git clone -b master --single-branch --depth 1 git@gitlab.com:StanislavKosyakov/unionandroid.git
    - cd unionandroid
    - git checkout -B increment_version_code
    - versionCode="$(./gradlew -Pci --console=plain -q incrementVersionCode)"
    - git add .
    - git commit -m "CI increment version code"
    - git push origin increment_version_code:master
     
    # Билд и отправка apk в телеграмм
    - ./gradlew app:assembleDebug
    - cd app/build/outputs/apk/debug
    - ls
    - files=( *.apk )
    - echo "${files[0]}"
    - curl --location --request POST https://api.telegram.org/bot$BOT_KEY/sendDocument?chat_id=$CHAT_ID --form document=@${files[0]}

    # Отправка комментария к каждой карточке в Done столбце
    - java -jar Rocket_Bot/releaseJar/UnionTrelloIntegrate-1.0-SNAPSHOT.jar "$TRELLO_TOKEN" "$TRELLO_API_KEY" "${files[0]}" "$TRELLO_LIST_ID"
  when: manual
