/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccountingObjectDtoV2
import org.openapitools.client.models.LinkedAdditionalFieldDtoV2
import org.openapitools.client.models.UnionItemDtoV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param userInserted 
 * @param userUpdated 
 * @param itemId 
 * @param extendedItem 
 * @param fieldId 
 * @param extendedField 
 * @param accountingObjectId 
 * @param extendedAccountingObject 
 */

data class AccountingObjectLinkedAdditionalFieldValueDtoV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "itemId")
    val itemId: kotlin.String? = null,

    @Json(name = "extendedItem")
    val extendedItem: UnionItemDtoV2? = null,

    @Json(name = "fieldId")
    val fieldId: kotlin.String? = null,

    @Json(name = "extendedField")
    val extendedField: LinkedAdditionalFieldDtoV2? = null,

    @Json(name = "accountingObjectId")
    val accountingObjectId: kotlin.String? = null,

    @Json(name = "extendedAccountingObject")
    val extendedAccountingObject: AccountingObjectDtoV2? = null

)

