/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param all 
 * @param empty 
 */

data class ApiSecurityUserRolesGetRequestsParametersParameterV2 (

    @Json(name = "all")
    val all: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "empty")
    val empty: kotlin.Boolean? = null

) : kotlin.collections.HashMap<String, kotlin.collections.List<*>>()

