/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.StructuralUnitDtoV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param userInserted 
 * @param userUpdated 
 * @param name 
 * @param address 
 * @param fullName 
 * @param organizationId 
 * @param inn 
 * @param kpp 
 * @param actualAddress 
 * @param legalAddress 
 * @param comment 
 * @param rfidValue 
 * @param nfcValue 
 * @param barcodeValue 
 * @param extendedOrganization 
 */

data class BuildingDtoV2 (

    @Json(name = "id")
    override val id: kotlin.String,

    @Json(name = "deleted")
    override val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "address")
    val address: kotlin.String? = null,

    @Json(name = "fullName")
    val fullName: kotlin.String? = null,

    @Json(name = "organizationId")
    val organizationId: kotlin.String? = null,

    @Json(name = "inn")
    val inn: kotlin.String? = null,

    @Json(name = "kpp")
    val kpp: kotlin.String? = null,

    @Json(name = "actualAddress")
    val actualAddress: kotlin.String? = null,

    @Json(name = "legalAddress")
    val legalAddress: kotlin.String? = null,

    @Json(name = "comment")
    val comment: kotlin.String? = null,

    @Json(name = "rfidValue")
    val rfidValue: kotlin.String? = null,

    @Json(name = "nfcValue")
    val nfcValue: kotlin.String? = null,

    @Json(name = "barcodeValue")
    val barcodeValue: kotlin.String? = null,

    @Json(name = "extendedOrganization")
    val extendedOrganization: StructuralUnitDtoV2? = null

): DeletedItemDto

