/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param authorId 
 * @param locationId 
 * @param departmentId 
 * @param accountingObjectId 
 * @param remainsId 
 * @param comment 
 * @param cancelReason 
 */

data class CancelNomenclatureApplicationRequestV2 (

    @Json(name = "authorId")
    val authorId: kotlin.String? = null,

    @Json(name = "locationId")
    val locationId: kotlin.String? = null,

    @Json(name = "departmentId")
    val departmentId: kotlin.String? = null,

    @Json(name = "accountingObjectId")
    val accountingObjectId: kotlin.String? = null,

    @Json(name = "remainsId")
    val remainsId: kotlin.String? = null,

    @Json(name = "comment")
    val comment: kotlin.String? = null,

    @Json(name = "cancelReason")
    val cancelReason: kotlin.String? = null

)

