/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param commissioningId 
 * @param extendedCommissioning 
 * @param name 
 * @param subName 
 * @param nomenclatureId 
 * @param extendedNomenclature 
 * @param nomenclatureGroupId 
 * @param extendedNomenclatureGroup 
 * @param serialNumber 
 * @param receptionDocumentNumber 
 * @param unitPrice 
 * @param structuralSubdivisionId 
 * @param extendedStructuralSubdivision 
 * @param locationId 
 * @param extendedLocation 
 * @param categoryId 
 * @param extendedCategory 
 * @param traceable 
 * @param molId 
 * @param extendedMol 
 * @param inventoryNumber 
 * @param organizationId 
 * @param extendedOrganization 
 */

data class CommissioningRecordDtoV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int?=null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "commissioningId")
    val commissioningId: kotlin.String? = null,

    @Json(name = "extendedCommissioning")
    val extendedCommissioning: CommissioningDtoV2? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "subName")
    val subName: kotlin.String? = null,

    @Json(name = "nomenclatureId")
    val nomenclatureId: kotlin.String? = null,

    @Json(name = "extendedNomenclature")
    val extendedNomenclature: NomenclatureDtoV2? = null,

    @Json(name = "nomenclatureGroupId")
    val nomenclatureGroupId: kotlin.String? = null,

    @Json(name = "extendedNomenclatureGroup")
    val extendedNomenclatureGroup: NomenclatureGroupDtoV2? = null,

    @Json(name = "serialNumber")
    val serialNumber: kotlin.String? = null,

    @Json(name = "receptionDocumentNumber")
    val receptionDocumentNumber: kotlin.String? = null,

    @Json(name = "unitPrice")
    val unitPrice: kotlin.String? = null,

    @Json(name = "structuralSubdivisionId")
    val structuralSubdivisionId: kotlin.String? = null,

    @Json(name = "extendedStructuralSubdivision")
    val extendedStructuralSubdivision: DepartmentDtoV2? = null,

    @Json(name = "locationId")
    val locationId: kotlin.String? = null,

    @Json(name = "extendedLocation")
    val extendedLocation: LocationDtoV2? = null,

    @Json(name = "categoryId")
    val categoryId: kotlin.String? = null,

    @Json(name = "extendedCategory")
    val extendedCategory: AccountingObjectCategoryDtoV2? = null,

    @Json(name = "traceable")
    val traceable: kotlin.Boolean? = null,

    @Json(name = "molId")
    val molId: kotlin.String? = null,

    @Json(name = "extendedMol")
    val extendedMol: EmployeeDtoV2? = null,

    @Json(name = "inventoryNumber")
    val inventoryNumber: kotlin.String? = null,

    @Json(name = "organizationId")
    val organizationId: kotlin.String? = null,

    @Json(name = "extendedOrganization")
    val extendedOrganization: OrganizationDtoV2? = null

)

