/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccountingObjectDtoV2
import org.openapitools.client.models.CommissioningDtoV2
import org.openapitools.client.models.EmployeeDtoV2
import org.openapitools.client.models.EnumDtoV2
import org.openapitools.client.models.LocationDtoV2
import org.openapitools.client.models.NomenclatureDtoV2
import org.openapitools.client.models.NomenclatureGroupDtoV2
import org.openapitools.client.models.RemainsDtoV2
import org.openapitools.client.models.StructuralUnitDtoV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param userInserted 
 * @param userUpdated 
 * @param commissioningId 
 * @param extendedCommissioning 
 * @param name 
 * @param subName 
 * @param nomenclatureId 
 * @param extendedNomenclature 
 * @param nomenclatureGroupId 
 * @param extendedNomenclatureGroup 
 * @param serialNumber 
 * @param receptionDocumentNumber 
 * @param unitPrice 
 * @param locationId 
 * @param extendedLocation 
 * @param categoryId 
 * @param extendedCategory 
 * @param traceable 
 * @param molId 
 * @param extendedMol 
 * @param inventoryNumber 
 * @param structuralUnitId 
 * @param extendedStructuralUnit 
 * @param accountingObjectId 
 * @param extendedAccountingObject 
 * @param resultAccountingObjectId 
 * @param extendedResultAccountingObject 
 * @param remainsId 
 * @param extendedRemains 
 */

data class CommissioningRecordDtoV2 (

    @Json(name = "id")
    override val id: kotlin.String,

    @Json(name = "deleted")
    override val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "commissioningId")
    val commissioningId: kotlin.String? = null,

    @Json(name = "extendedCommissioning")
    val extendedCommissioning: CommissioningDtoV2? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "subName")
    val subName: kotlin.String? = null,

    @Json(name = "nomenclatureId")
    val nomenclatureId: kotlin.String? = null,

    @Json(name = "extendedNomenclature")
    val extendedNomenclature: NomenclatureDtoV2? = null,

    @Json(name = "nomenclatureGroupId")
    val nomenclatureGroupId: kotlin.String? = null,

    @Json(name = "extendedNomenclatureGroup")
    val extendedNomenclatureGroup: NomenclatureGroupDtoV2? = null,

    @Json(name = "serialNumber")
    val serialNumber: kotlin.String? = null,

    @Json(name = "receptionDocumentNumber")
    val receptionDocumentNumber: kotlin.String? = null,

    @Json(name = "unitPrice")
    val unitPrice: kotlin.String? = null,

    @Json(name = "locationId")
    val locationId: kotlin.String? = null,

    @Json(name = "extendedLocation")
    val extendedLocation: LocationDtoV2? = null,

    @Json(name = "categoryId")
    val categoryId: kotlin.String? = null,

    @Json(name = "extendedCategory")
    val extendedCategory: EnumDtoV2? = null,

    @Json(name = "traceable")
    val traceable: kotlin.Boolean? = null,

    @Json(name = "molId")
    val molId: kotlin.String? = null,

    @Json(name = "extendedMol")
    val extendedMol: EmployeeDtoV2? = null,

    @Json(name = "inventoryNumber")
    val inventoryNumber: kotlin.String? = null,

    @Json(name = "structuralUnitId")
    val structuralUnitId: kotlin.String? = null,

    @Json(name = "extendedStructuralUnit")
    val extendedStructuralUnit: StructuralUnitDtoV2? = null,

    @Json(name = "accountingObjectId")
    val accountingObjectId: kotlin.String? = null,

    @Json(name = "extendedAccountingObject")
    val extendedAccountingObject: AccountingObjectDtoV2? = null,

    @Json(name = "resultAccountingObjectId")
    val resultAccountingObjectId: kotlin.String? = null,

    @Json(name = "extendedResultAccountingObject")
    val extendedResultAccountingObject: AccountingObjectDtoV2? = null,

    @Json(name = "remainsId")
    val remainsId: kotlin.String? = null,

    @Json(name = "extendedRemains")
    val extendedRemains: RemainsDtoV2? = null

): DeletedItemDto

