/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param newCount 
 * @param orderItemId 
 * @param receptionItemCategoryId 
 */

data class CreateReceptionRequestItemsV2 (

    @Json(name = "newCount")
    val newCount: kotlin.Int? = null,

    @Json(name = "orderItemId")
    val orderItemId: kotlin.String? = null,

    @Json(name = "receptionItemCategoryId")
    val receptionItemCategoryId: kotlin.String? = null

)

