/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.StructuralUnitV2
import org.openapitools.client.models.SyncItemV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param dateInsert 
 * @param dateUpdate 
 * @param userInserted 
 * @param userUpdated 
 * @param version 
 * @param catalogItemName 
 * @param code 
 * @param firstname 
 * @param lastname 
 * @param patronymic 
 * @param birthdate 
 * @param structuralUnit 
 * @param subdivision 
 * @param post 
 * @param number 
 * @param card 
 * @param balanceUnit 
 * @param nfc 
 * @param employeeStatus 
 * @param serviceNumber 
 * @param oldSystemId 
 * @param cascadeItems 
 */

data class EmployeeV2 (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "firstname")
    val firstname: kotlin.String? = null,

    @Json(name = "lastname")
    val lastname: kotlin.String? = null,

    @Json(name = "patronymic")
    val patronymic: kotlin.String? = null,

    @Json(name = "birthdate")
    val birthdate: kotlin.String? = null,

    @Json(name = "structuralUnit")
    val structuralUnit: StructuralUnitV2? = null,

    @Json(name = "subdivision")
    val subdivision: kotlin.String? = null,

    @Json(name = "post")
    val post: kotlin.String? = null,

    @Json(name = "number")
    val number: kotlin.String? = null,

    @Json(name = "card")
    val card: kotlin.String? = null,

    @Json(name = "balanceUnit")
    val balanceUnit: StructuralUnitV2? = null,

    @Json(name = "nfc")
    val nfc: kotlin.String? = null,

    @Json(name = "employeeStatus")
    val employeeStatus: kotlin.String? = null,

    @Json(name = "serviceNumber")
    val serviceNumber: kotlin.String? = null,

    @Json(name = "oldSystemId")
    val oldSystemId: kotlin.String? = null,

    @Json(name = "cascadeItems")
    val cascadeItems: kotlin.collections.List<SyncItemV2>? = null

)

