/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.StructuralUnitDtoV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param userInserted 
 * @param userUpdated 
 * @param firstname 
 * @param lastname 
 * @param patronymic 
 * @param birthdate 
 * @param balanceUnitId 
 * @param extendedBalanceUnit 
 * @param structuralUnitId 
 * @param extendedStructuralUnit 
 * @param post 
 * @param number 
 * @param card 
 * @param nfc 
 * @param employeeStatusId 
 * @param serviceNumber 
 */

data class EmployeeDtoV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "firstname")
    val firstname: kotlin.String? = null,

    @Json(name = "lastname")
    val lastname: kotlin.String? = null,

    @Json(name = "patronymic")
    val patronymic: kotlin.String? = null,

    @Json(name = "birthdate")
    val birthdate: kotlin.String? = null,

    @Json(name = "balanceUnitId")
    val balanceUnitId: kotlin.String? = null,

    @Json(name = "extendedBalanceUnit")
    val extendedBalanceUnit: StructuralUnitDtoV2? = null,

    @Json(name = "structuralUnitId")
    val structuralUnitId: kotlin.String? = null,

    @Json(name = "extendedStructuralUnit")
    val extendedStructuralUnit: StructuralUnitDtoV2? = null,

    @Json(name = "post")
    val post: kotlin.String? = null,

    @Json(name = "number")
    val number: kotlin.String? = null,

    @Json(name = "card")
    val card: kotlin.String? = null,

    @Json(name = "nfc")
    val nfc: kotlin.String? = null,

    @Json(name = "employeeStatusId")
    val employeeStatusId: kotlin.String? = null,

    @Json(name = "serviceNumber")
    val serviceNumber: kotlin.String? = null

)

