/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param entityModelType 
 * @param scopes 
 * @param restActions 
 * @param child 
 */

data class EntityModelV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "entityModelType")
    val entityModelType: EntityModelV2.EntityModelType? = null,

    @Json(name = "scopes")
    val scopes: kotlin.collections.Set<ScopeV2>? = null,

    @Json(name = "restActions")
    val restActions: kotlin.collections.Set<EntityModelV2.RestActions>? = null,

    @Json(name = "child")
    val child: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: sECURITY,cATALOGS,dOCUMENTS,iNVENTORIES,tASKS,rEPORTS
     */
    enum class EntityModelType(val value: kotlin.String) {
        @Json(name = "SECURITY") sECURITY("SECURITY"),
        @Json(name = "CATALOGS") cATALOGS("CATALOGS"),
        @Json(name = "DOCUMENTS") dOCUMENTS("DOCUMENTS"),
        @Json(name = "INVENTORIES") iNVENTORIES("INVENTORIES"),
        @Json(name = "TASKS") tASKS("TASKS"),
        @Json(name = "REPORTS") rEPORTS("REPORTS");
    }
    /**
     * 
     *
     * Values: cREATE,rEAD,uPDATE,dELETE
     */
    enum class RestActions(val value: kotlin.String) {
        @Json(name = "CREATE") cREATE("CREATE"),
        @Json(name = "READ") rEAD("READ"),
        @Json(name = "UPDATE") uPDATE("UPDATE"),
        @Json(name = "DELETE") dELETE("DELETE");
    }
}

