/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param inventoryNumberTemplateId 
 * @param useDefaultTemplate 
 */

data class GenerateInventoryNumberRequestV2 (

    @Json(name = "inventoryNumberTemplateId")
    val inventoryNumberTemplateId: kotlin.String? = null,

    @Json(name = "useDefaultTemplate")
    val useDefaultTemplate: kotlin.Boolean? = null

)

