/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EmployeeDtoV2
import org.openapitools.client.models.PersonV2

import com.squareup.moshi.Json

/**
 *
 *
 * @param extended
 * @param errorCode
 * @param list
 * @param page
 * @param propertySize
 * @param total
 * @param superuser
 * @param person
 * @param employee
 */

data class GetMyPermissionsResponseV2(

    @Json(name = "extended")
    val extended: kotlin.Boolean? = null,

    @Json(name = "errorCode")
    val errorCode: kotlin.String? = null,

    @Json(name = "list")
    val list: List<PermissionDtoV2>? = null,

    @Json(name = "page")
    val page: kotlin.Long? = null,

    @Json(name = "size")
    val propertySize: kotlin.Long? = null,

    @Json(name = "total")
    val total: kotlin.Long? = null,

    @Json(name = "superuser")
    val superuser: kotlin.Boolean? = null,

    @Json(name = "person")
    val person: PersonV2? = null,

    @Json(name = "employee")
    val employee: EmployeeDtoV2? = null

)

