/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EntityModelV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param requestId 
 * @param itemsCount 
 * @param localDateTime 
 * @param entityModel 
 * @param table 
 */

data class ImportPartInformationV2 (

    @Json(name = "requestId")
    val requestId: kotlin.String? = null,

    @Json(name = "itemsCount")
    val itemsCount: kotlin.Int? = null,

    @Json(name = "localDateTime")
    val localDateTime: kotlin.String? = null,

    @Json(name = "entityModel")
    val entityModel: EntityModelV2? = null,

    @Json(name = "table")
    val table: kotlin.String? = null

)

