/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json
import java.math.BigDecimal
import org.openapitools.client.models.AccountingObjectDtoV2
import org.openapitools.client.models.DeletedItemDto
import org.openapitools.client.models.EnumDtoV2
import org.openapitools.client.models.InventoryDtoV2

/**
 *
 *
 * @param id
 * @param deleted
 * @param version
 * @param dateInsert
 * @param dateUpdate
 * @param catalogItemName
 * @param code
 * @param userInserted
 * @param userUpdated
 * @param inventoryId
 * @param accountingObjectId
 * @param inventoryRecordStatusId
 * @param extendedInventory
 * @param extendedAccountingObject
 * @param extendedInventoryRecordStatus
 */

data class InventoryNomenclatureRecordDtoV2(

    @Json(name = "id")
    override val id: kotlin.String,

    @Json(name = "deleted")
    override val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "inventoryId")
    val inventoryId: kotlin.String? = null,

    @Json(name = "nomenclatureId")
    val nomenclatureId: String? = null,

    @Json(name = "extendedNomenclature")
    val extendedNomenclature: NomenclatureDtoV2? = null,

    @Json(name = "expectedCount")
    val expectedCount: Long? = null,

    @Json(name = "actualCount")
    val actualCount: Long? = null,

    @Json(name = "consignment")
    val consignment: String? = null,

    @Json(name = "bookkeepingInvoice")
    val bookKeepingInvoice: BigDecimal? = null,

    @Json(name = "price")
    val price: String? = null,

    @Json(name = "extendedInventory")
    val extendedInventory: InventoryDtoV2? = null,
) : DeletedItemDto