/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccountingObjectDtoV2
import org.openapitools.client.models.InventoryResultDtoV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param userInserted 
 * @param userUpdated 
 * @param accountingObjectId 
 * @param extendedAccountingObject 
 * @param extendedInventoryResult 
 * @param inventoryRecordStatusId 
 * @param lastInventoryTime 
 * @param checked 
 * @param inventoryResultId 
 */

data class InventoryResultRecordDtoV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "accountingObjectId")
    val accountingObjectId: kotlin.String? = null,

    @Json(name = "extendedAccountingObject")
    val extendedAccountingObject: AccountingObjectDtoV2? = null,

    @Json(name = "extendedInventoryResult")
    val extendedInventoryResult: InventoryResultDtoV2? = null,

    @Json(name = "inventoryRecordStatusId")
    val inventoryRecordStatusId: kotlin.String? = null,

    @Json(name = "lastInventoryTime")
    val lastInventoryTime: kotlin.String? = null,

    @Json(name = "checked")
    val checked: kotlin.Boolean? = null,

    @Json(name = "inventoryResultId")
    val inventoryResultId: kotlin.String? = null

)

