/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param findRecordsCount 
 * @param notFindRecordsCount 
 * @param newRecordsCount 
 * @param byPlanCount 
 */

data class InventoryRecordStatusesV2 (

    @Json(name = "findRecordsCount")
    val findRecordsCount: kotlin.Long? = null,

    @Json(name = "notFindRecordsCount")
    val notFindRecordsCount: kotlin.Long? = null,

    @Json(name = "newRecordsCount")
    val newRecordsCount: kotlin.Long? = null,

    @Json(name = "byPlanCount")
    val byPlanCount: kotlin.Long? = null

)

