/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param templateNumber 
 * @param templateName 
 * @param inventoryNumberLength 
 * @param splitter 
 * @param prefixLength 
 * @param byDefault 
 * @param customPrefix 
 * @param inventoryNumberTemplatePrefixSourceId 
 * @param extendedInventoryNumberTemplatePrefixSource 
 */

data class InventoryNumberTemplateDtoV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int?=null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "templateNumber")
    val templateNumber: kotlin.String? = null,

    @Json(name = "templateName")
    val templateName: kotlin.String? = null,

    @Json(name = "inventoryNumberLength")
    val inventoryNumberLength: kotlin.Int? = null,

    @Json(name = "splitter")
    val splitter: kotlin.String? = null,

    @Json(name = "prefixLength")
    val prefixLength: kotlin.String? = null,

    @Json(name = "byDefault")
    val byDefault: kotlin.Boolean? = null,

    @Json(name = "customPrefix")
    val customPrefix: kotlin.Boolean? = null,

    @Json(name = "inventoryNumberTemplatePrefixSourceId")
    val inventoryNumberTemplatePrefixSourceId: kotlin.String? = null,

    @Json(name = "extendedInventoryNumberTemplatePrefixSource")
    val extendedInventoryNumberTemplatePrefixSource: InventoryNumberTemplatePrefixSourceDtoV2? = null

)

