/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EmployeeDtoV2
import org.openapitools.client.models.EnumDtoV2
import org.openapitools.client.models.LocationDtoV2
import org.openapitools.client.models.StructuralUnitDtoV2

import com.squareup.moshi.Json

/**
 *
 *
 * @param id
 * @param deleted
 * @param version
 * @param structuralUnitId
 * @param inventoryStateId
 * @param inventoryTypeId
 * @param dateInsert
 * @param dateUpdate
 * @param catalogItemName
 * @param code
 * @param userInserted
 * @param userUpdated
 * @param creationDate
 * @param internalNumber
 * @param locationId
 * @param molId
 * @param name
 * @param extendedStructuralUnit
 * @param extendedLocation
 * @param extendedMol
 * @param extendedInventoryState
 * @param extendedInventoryType
 * @param inventoryBaseId
 * @param extendedInventoryBase
 * @param comment
 */

data class InventoryDtoV2(

    @Json(name = "id")
    override val id: kotlin.String,

    @Json(name = "deleted")
    override val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "structuralUnitId")
    val structuralUnitId: kotlin.String,

    @Json(name = "inventoryStateId")
    val inventoryStateId: kotlin.String,

    @Json(name = "inventoryTypeId")
    val inventoryTypeId: kotlin.String,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "creationDate")
    val creationDate: kotlin.String? = null,

    @Json(name = "internalNumber")
    val internalNumber: kotlin.String? = null,

    @Json(name = "locationId")
    val locationId: kotlin.String? = null,

    @Json(name = "molId")
    val molId: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "extendedStructuralUnit")
    val extendedStructuralUnit: StructuralUnitDtoV2? = null,

    @Json(name = "extendedLocation")
    val extendedLocation: LocationDtoV2? = null,

    @Json(name = "extendedMol")
    val extendedMol: EmployeeDtoV2? = null,

    @Json(name = "extendedInventoryState")
    val extendedInventoryState: EnumDtoV2? = null,

    @Json(name = "extendedInventoryType")
    val extendedInventoryType: EnumDtoV2? = null,

    @Json(name = "inventoryBaseId")
    val inventoryBaseId: kotlin.String? = null,

    @Json(name = "extendedInventoryBase")
    val extendedInventoryBase: EnumDtoV2? = null,

    @Json(name = "comment")
    val comment: kotlin.String? = null

) : DeletedItemDto

