/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param premises 
 * @param totalWorkPlacesCount 
 * @param busyByAccountingObjectWorkPlacesCount 
 * @param freeWorkPlacesCount 
 * @param busyByAccountingObjectWithoutOwnerWorkPlacesCount 
 */

data class PremisesInformationDtoV2 (

    @Json(name = "premises")
    val premises: LocationDtoV2? = null,

    @Json(name = "totalWorkPlacesCount")
    val totalWorkPlacesCount: kotlin.Int? = null,

    @Json(name = "busyByAccountingObjectWorkPlacesCount")
    val busyByAccountingObjectWorkPlacesCount: kotlin.Int? = null,

    @Json(name = "freeWorkPlacesCount")
    val freeWorkPlacesCount: kotlin.Int? = null,

    @Json(name = "busyByAccountingObjectWithoutOwnerWorkPlacesCount")
    val busyByAccountingObjectWithoutOwnerWorkPlacesCount: kotlin.Int? = null

)

