/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param organizationId 
 * @param locationId 
 * @param molId 
 * @param searchQuery 
 * @param page 
 * @param propertySize 
 */

data class PreviewInventoryRequestV2 (

    @Json(name = "organizationId")
    val organizationId: kotlin.String? = null,

    @Json(name = "locationId")
    val locationId: kotlin.String? = null,

    @Json(name = "molId")
    val molId: kotlin.String? = null,

    @Json(name = "searchQuery")
    val searchQuery: kotlin.String? = null,

    @Json(name = "page")
    val page: kotlin.Int? = null,

    @Json(name = "size")
    val propertySize: kotlin.Int? = null

)

