/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param name 
 * @param `value` 
 * @param width 
 * @param height 
 * @param dpmm 
 * @param printObjectTypeId 
 * @param elementsJson 
 * @param rfidProperty 
 * @param extendedPrintObjectType 
 */

data class PrintTemplateDtoV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int?=null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "value")
    val `value`: kotlin.String? = null,

    @Json(name = "width")
    val width: kotlin.Int? = null,

    @Json(name = "height")
    val height: kotlin.Int? = null,

    @Json(name = "dpmm")
    val dpmm: kotlin.Int? = null,

    @Json(name = "printObjectTypeId")
    val printObjectTypeId: kotlin.String? = null,

    @Json(name = "elementsJson")
    val elementsJson: kotlin.String? = null,

    @Json(name = "rfidProperty")
    val rfidProperty: kotlin.String? = null,

    @Json(name = "extendedPrintObjectType")
    val extendedPrintObjectType: PrintObjectTypeDtoV2? = null

)

