/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EmployeeDtoV2
import org.openapitools.client.models.EnumDtoV2
import org.openapitools.client.models.PrintTemplateDtoV2
import org.openapitools.client.models.StructuralUnitDtoV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param userInserted 
 * @param userUpdated 
 * @param creationDate 
 * @param structuralUnitId 
 * @param responsibleId 
 * @param printJobStatusId 
 * @param printObjectTypeId 
 * @param printTemplateId 
 * @param extendedStructuralUnit 
 * @param extendedResponsible 
 * @param extendedPrintJobStatus 
 * @param extendedPrintObjectType 
 * @param extendedPrintTemplate 
 */

data class PrintJobDtoV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "creationDate")
    val creationDate: kotlin.String? = null,

    @Json(name = "structuralUnitId")
    val structuralUnitId: kotlin.String? = null,

    @Json(name = "responsibleId")
    val responsibleId: kotlin.String? = null,

    @Json(name = "printJobStatusId")
    val printJobStatusId: kotlin.String? = null,

    @Json(name = "printObjectTypeId")
    val printObjectTypeId: kotlin.String? = null,

    @Json(name = "printTemplateId")
    val printTemplateId: kotlin.String? = null,

    @Json(name = "extendedStructuralUnit")
    val extendedStructuralUnit: StructuralUnitDtoV2? = null,

    @Json(name = "extendedResponsible")
    val extendedResponsible: EmployeeDtoV2? = null,

    @Json(name = "extendedPrintJobStatus")
    val extendedPrintJobStatus: EnumDtoV2? = null,

    @Json(name = "extendedPrintObjectType")
    val extendedPrintObjectType: EnumDtoV2? = null,

    @Json(name = "extendedPrintTemplate")
    val extendedPrintTemplate: PrintTemplateDtoV2? = null

)

