/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param extended 
 * @param errorCode 
 * @param `value` 
 */

data class PutResponseV2 (

    @Json(name = "extended")
    val extended: kotlin.Boolean? = null,

    @Json(name = "errorCode")
    val errorCode: kotlin.String? = null,

    @Json(name = "value")
    val `value`: kotlin.Any? = null

)

