/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CounterpartyDtoV2
import org.openapitools.client.models.EmployeeDtoV2
import org.openapitools.client.models.EnumDtoV2
import org.openapitools.client.models.LocationDtoV2
import org.openapitools.client.models.StructuralUnitDtoV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param userInserted 
 * @param userUpdated 
 * @param structuralUnitId 
 * @param extendedStructuralUnit 
 * @param locationId 
 * @param extendedLocation 
 * @param creationDate 
 * @param estimatedEndDate 
 * @param responsibleEmployeeId 
 * @param extendedResponsibleEmployee 
 * @param responsibleCounterpartyId 
 * @param extendedResponsibleCounterparty 
 * @param repairStatusId 
 * @param extendedRepairStatus 
 */

data class RepairDtoV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "structuralUnitId")
    val structuralUnitId: kotlin.String? = null,

    @Json(name = "extendedStructuralUnit")
    val extendedStructuralUnit: StructuralUnitDtoV2? = null,

    @Json(name = "locationId")
    val locationId: kotlin.String? = null,

    @Json(name = "extendedLocation")
    val extendedLocation: LocationDtoV2? = null,

    @Json(name = "creationDate")
    val creationDate: kotlin.String? = null,

    @Json(name = "estimatedEndDate")
    val estimatedEndDate: kotlin.String? = null,

    @Json(name = "responsibleEmployeeId")
    val responsibleEmployeeId: kotlin.String? = null,

    @Json(name = "extendedResponsibleEmployee")
    val extendedResponsibleEmployee: EmployeeDtoV2? = null,

    @Json(name = "responsibleCounterpartyId")
    val responsibleCounterpartyId: kotlin.String? = null,

    @Json(name = "extendedResponsibleCounterparty")
    val extendedResponsibleCounterparty: CounterpartyDtoV2? = null,

    @Json(name = "repairStatusId")
    val repairStatusId: kotlin.String? = null,

    @Json(name = "extendedRepairStatus")
    val extendedRepairStatus: EnumDtoV2? = null

)

