/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RemainsDtoV2
import org.openapitools.client.models.RepairRecordDtoV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param userInserted 
 * @param userUpdated 
 * @param repairRecordId 
 * @param extendedRepairRecord 
 * @param remainsId 
 * @param extendedRemains 
 * @param count 
 */

data class RepairRecordRemainsDtoV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "repairRecordId")
    val repairRecordId: kotlin.String? = null,

    @Json(name = "extendedRepairRecord")
    val extendedRepairRecord: RepairRecordDtoV2? = null,

    @Json(name = "remainsId")
    val remainsId: kotlin.String? = null,

    @Json(name = "extendedRemains")
    val extendedRemains: RemainsDtoV2? = null,

    @Json(name = "count")
    val count: java.math.BigDecimal? = null

)

