/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param repairRecordStatusId 
 * @param repairRecordId 
 * @param locationForReturnId 
 * @param accountingObjectId 
 * @param repairId 
 * @param changed 
 * @param extendedRepairRecordRemains 
 */

data class SaveRepairRequestRecordItemV2 (

    @Json(name = "repairRecordStatusId")
    val repairRecordStatusId: kotlin.String? = null,

    @Json(name = "repairRecordId")
    val repairRecordId: kotlin.String? = null,

    @Json(name = "locationForReturnId")
    val locationForReturnId: kotlin.String? = null,

    @Json(name = "accountingObjectId")
    val accountingObjectId: kotlin.String? = null,

    @Json(name = "repairId")
    val repairId: kotlin.String? = null,

    @Json(name = "changed")
    val changed: kotlin.Boolean? = null,

    @Json(name = "extendedRepairRecordRemains")
    val extendedRepairRecordRemains: kotlin.collections.List<SaveRepairRequestRemainsItemV2>? = null

)

