/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RepairDtoV2
import org.openapitools.client.models.SaveRepairRequestRecordItemV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param extendedRepair 
 * @param extendedRecords 
 */

data class SaveRepairRequestV2 (

    @Json(name = "extendedRepair")
    val extendedRepair: RepairDtoV2? = null,

    @Json(name = "extendedRecords")
    val extendedRecords: kotlin.collections.List<SaveRepairRequestRecordItemV2>? = null

)

