/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param sorted 
 * @param unsorted 
 * @param empty 
 */

data class SortV2 (

    @Json(name = "sorted")
    val sorted: kotlin.Boolean? = null,

    @Json(name = "unsorted")
    val unsorted: kotlin.Boolean? = null,

    @Json(name = "empty")
    val empty: kotlin.Boolean? = null

)

