/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ExportPartBufferInformationV2
import org.openapitools.client.models.ImportPartBufferInformationV2

import com.squareup.moshi.Json

/**
 *
 *
 * @param id
 * @param importPartBufferInformation
 * @param exportPartBufferInformation
 * @param importStart
 * @param importComplete
 * @param exportStart
 * @param exportComplete
 * @param syncComplete
 */

data class SyncInformationV2(

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "importPartBufferInformation")
    val importPartBufferInformation: ImportPartBufferInformationV2,

    @Json(name = "exportPartBufferInformation")
    val exportPartBufferInformation: ExportPartBufferInformationV2,

    @Json(name = "importStart")
    val importStart: kotlin.Boolean? = null,

    @Json(name = "importComplete")
    val importComplete: kotlin.Boolean? = null,

    @Json(name = "exportStart")
    val exportStart: kotlin.Boolean? = null,

    @Json(name = "exportComplete")
    val exportComplete: kotlin.Boolean? = null,

    @Json(name = "syncComplete")
    val syncComplete: kotlin.Boolean? = null,

    @Json(name = "terminalPrefix")
    val terminalPrefix: String

)

