/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EmployeeDtoV2
import org.openapitools.client.models.EnumDtoV2
import org.openapitools.client.models.LocationDtoV2
import org.openapitools.client.models.StructuralUnitDtoV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param userInserted 
 * @param userUpdated 
 * @param creationDate 
 * @param responsibleId 
 * @param extendedResponsible 
 * @param receivingId 
 * @param extendedReceiving 
 * @param locationToId 
 * @param extendedLocationTo 
 * @param locationFromId 
 * @param extendedLocationFrom 
 * @param structuralUnitFromId 
 * @param structuralUnitToId 
 * @param molReceivingId 
 * @param extendedMolReceiving 
 * @param vehicleId 
 * @param extendedVehicleId 
 * @param typeId 
 * @param extendedType 
 * @param statusId 
 * @param extendedStatus 
 * @param organizationId 
 * @param extendedOrganization 
 * @param extendedStructuralUnitFrom 
 * @param extendedStructuralUnitTo 
 */

data class TransitDtoV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "creationDate")
    val creationDate: kotlin.String? = null,

    @Json(name = "responsibleId")
    val responsibleId: kotlin.String? = null,

    @Json(name = "extendedResponsible")
    val extendedResponsible: EmployeeDtoV2? = null,

    @Json(name = "receivingId")
    val receivingId: kotlin.String? = null,

    @Json(name = "extendedReceiving")
    val extendedReceiving: EmployeeDtoV2? = null,

    @Json(name = "locationToId")
    val locationToId: kotlin.String? = null,

    @Json(name = "extendedLocationTo")
    val extendedLocationTo: LocationDtoV2? = null,

    @Json(name = "locationFromId")
    val locationFromId: kotlin.String? = null,

    @Json(name = "extendedLocationFrom")
    val extendedLocationFrom: LocationDtoV2? = null,

    @Json(name = "structuralUnitFromId")
    val structuralUnitFromId: kotlin.String? = null,

    @Json(name = "structuralUnitToId")
    val structuralUnitToId: kotlin.String? = null,

    @Json(name = "molReceivingId")
    val molReceivingId: kotlin.String? = null,

    @Json(name = "extendedMolReceiving")
    val extendedMolReceiving: EmployeeDtoV2? = null,

    @Json(name = "vehicleId")
    val vehicleId: kotlin.String? = null,

    @Json(name = "extendedVehicleId")
    val extendedVehicleId: LocationDtoV2? = null,

    @Json(name = "typeId")
    val typeId: kotlin.String? = null,

    @Json(name = "extendedType")
    val extendedType: EnumDtoV2? = null,

    @Json(name = "statusId")
    val statusId: kotlin.String? = null,

    @Json(name = "extendedStatus")
    val extendedStatus: EnumDtoV2? = null,

    @Json(name = "organizationId")
    val organizationId: kotlin.String? = null,

    @Json(name = "extendedOrganization")
    val extendedOrganization: StructuralUnitDtoV2? = null,

    @Json(name = "extendedStructuralUnitFrom")
    val extendedStructuralUnitFrom: StructuralUnitDtoV2? = null,

    @Json(name = "extendedStructuralUnitTo")
    val extendedStructuralUnitTo: StructuralUnitDtoV2? = null

)

