/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EmployeeDtoV2
import org.openapitools.client.models.EnumDtoV2
import org.openapitools.client.models.LocationDtoV2
import org.openapitools.client.models.ReceptionDtoV2
import org.openapitools.client.models.StructuralUnitDtoV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param userInserted 
 * @param userUpdated 
 * @param creationDate 
 * @param structuralUnitId 
 * @param extendedStructuralUnit 
 * @param responsibleId 
 * @param extendedResponsible 
 * @param locationId 
 * @param extendedLocation 
 * @param statusId 
 * @param extendedStatus 
 * @param receptionId 
 * @param extendedReception 
 */

data class WriteOffDtoV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "creationDate")
    val creationDate: kotlin.String? = null,

    @Json(name = "structuralUnitId")
    val structuralUnitId: kotlin.String? = null,

    @Json(name = "extendedStructuralUnit")
    val extendedStructuralUnit: StructuralUnitDtoV2? = null,

    @Json(name = "responsibleId")
    val responsibleId: kotlin.String? = null,

    @Json(name = "extendedResponsible")
    val extendedResponsible: EmployeeDtoV2? = null,

    @Json(name = "locationId")
    val locationId: kotlin.String? = null,

    @Json(name = "extendedLocation")
    val extendedLocation: LocationDtoV2? = null,

    @Json(name = "statusId")
    val statusId: kotlin.String? = null,

    @Json(name = "extendedStatus")
    val extendedStatus: EnumDtoV2? = null,

    @Json(name = "receptionId")
    val receptionId: kotlin.String? = null,

    @Json(name = "extendedReception")
    val extendedReception: ReceptionDtoV2? = null

)

