/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccountingObjectDtoV2
import org.openapitools.client.models.EnumDtoV2
import org.openapitools.client.models.WriteOffDtoV2

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param code 
 * @param userInserted 
 * @param userUpdated 
 * @param writeOffId 
 * @param extendedWriteOff 
 * @param accountingObjectId 
 * @param extendedAccountingObject 
 * @param createComponents 
 * @param writeOffReasonsId 
 * @param extendedWriteOffReasons 
 * @param destructionConditionsId 
 * @param extendedDestructionConditions 
 * @param professionalJudgment 
 */

data class WriteOffRecordDtoV2 (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int? = null,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "userInserted")
    val userInserted: kotlin.String? = null,

    @Json(name = "userUpdated")
    val userUpdated: kotlin.String? = null,

    @Json(name = "writeOffId")
    val writeOffId: kotlin.String? = null,

    @Json(name = "extendedWriteOff")
    val extendedWriteOff: WriteOffDtoV2? = null,

    @Json(name = "accountingObjectId")
    val accountingObjectId: kotlin.String? = null,

    @Json(name = "extendedAccountingObject")
    val extendedAccountingObject: AccountingObjectDtoV2? = null,

    @Json(name = "createComponents")
    val createComponents: kotlin.Boolean? = null,

    @Json(name = "writeOffReasonsId")
    val writeOffReasonsId: kotlin.String? = null,

    @Json(name = "extendedWriteOffReasons")
    val extendedWriteOffReasons: EnumDtoV2? = null,

    @Json(name = "destructionConditionsId")
    val destructionConditionsId: kotlin.String? = null,

    @Json(name = "extendedDestructionConditions")
    val extendedDestructionConditions: EnumDtoV2? = null,

    @Json(name = "professionalJudgment")
    val professionalJudgment: kotlin.String? = null

)

