/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param organizationId 
 * @param locationId 
 * @param estimatedEndDate 
 * @param responsibleEmployeeId 
 * @param responsibleCounterpartyId 
 * @param records 
 */

data class CreateRepairRequest (

    @Json(name = "organizationId")
    val organizationId: kotlin.String? = null,

    @Json(name = "locationId")
    val locationId: kotlin.String? = null,

    @Json(name = "estimatedEndDate")
    val estimatedEndDate: kotlin.String? = null,

    @Json(name = "responsibleEmployeeId")
    val responsibleEmployeeId: kotlin.String? = null,

    @Json(name = "responsibleCounterpartyId")
    val responsibleCounterpartyId: kotlin.String? = null,

    @Json(name = "records")
    val records: kotlin.collections.List<kotlin.String>? = null

)

