/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 *
 *
 * @param id
 * @param deleted
 * @param dateInsert
 * @param dateUpdate
 * @param version
 * @param catalogItemName
 * @param name
 * @param inn
 * @param kpp
 * @param actualAddress
 * @param legalAddress
 * @param comment
 * @param cascadeItems
 */

data class CustomOrganizationDto(

    @Json(name = "id")
    val id: String,

    @Json(name = "deleted")
    val deleted: Boolean? = null,

    @Json(name = "dateInsert")
    val dateInsert: String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: String? = null,

    @Json(name = "version")
    val version: Int? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: String? = null,

    @Json(name = "name")
    val name: String? = null,

    @Json(name = "inn")
    val inn: String? = null,

    @Json(name = "kpp")
    val kpp: String? = null,

    @Json(name = "actualAddress")
    val actualAddress: String? = null,

    @Json(name = "legalAddress")
    val legalAddress: String? = null,

    @Json(name = "comment")
    val comment: String? = null,

    @Json(name = "employeeId")
    val employeeId: String?

)

