/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param deleted 
 * @param version 
 * @param dateInsert 
 * @param dateUpdate 
 * @param catalogItemName 
 * @param unionUserId 
 * @param unionRoleId 
 * @param extendedUnionUserDto 
 * @param extendedUnionRoleDto 
 */

data class UserRoleDto (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "deleted")
    val deleted: kotlin.Boolean,

    @Json(name = "version")
    val version: kotlin.Int,

    @Json(name = "dateInsert")
    val dateInsert: kotlin.String? = null,

    @Json(name = "dateUpdate")
    val dateUpdate: kotlin.String? = null,

    @Json(name = "catalogItemName")
    val catalogItemName: kotlin.String? = null,

    @Json(name = "unionUserId")
    val unionUserId: kotlin.String? = null,

    @Json(name = "unionRoleId")
    val unionRoleId: kotlin.String? = null,

    @Json(name = "extendedUnionUserDto")
    val extendedUnionUserDto: UnionUserDto? = null,

    @Json(name = "extendedUnionRoleDto")
    val extendedUnionRoleDto: UnionRoleDto? = null

)

